# -*- coding: utf-8 -*-
"""SecondBool_InputHandler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14K4N8VXvwUE6AHDZLbJ3udLkvRK1Cz53
"""

"""
2nd Boolean Input Handler
---------------------------------------------

Input 1: deadline_datetime -> datetime object (or string) for when the task is due
Input 2: task_length_hours -> float, estimated number of hours to complete the task

Output: 1 if time_left > time_required  (Not Urgent)
        0 if time_left <= time_required (Urgent)
"""

from datetime import datetime


def get_time_left_hours(deadline_datetime, current_datetime=None):
    """
    Calculates the number of hours remaining until the deadline.

    Args:
        deadline_datetime (datetime | str): The deadline. If a string, it should
            be in ISO format, e.g. "2026-08-20 23:59".
        current_datetime (datetime, optional): Defaults to now if not provided.

    Returns:
        float: hours remaining until deadline (can be negative if overdue).
    """
    if isinstance(deadline_datetime, str):
        deadline_datetime = datetime.fromisoformat(deadline_datetime)

    if current_datetime is None:
        current_datetime = datetime.now()

    delta = deadline_datetime - current_datetime
    return delta.total_seconds() / 3600


def is_time_left_greater(deadline_datetime, task_length_hours, current_datetime=None):
    """
    Args:
        deadline_datetime (datetime | str): The task's deadline.
        task_length_hours (float): Estimated hours required to complete the task.
        current_datetime (datetime, optional): Defaults to now if not provided.

    Returns:
        int: 1 if time_left > task_length_hours (Not Urgent)
             0 if time_left <= task_length_hours (Urgent)
    """
    time_left_hours = get_time_left_hours(deadline_datetime, current_datetime)
    return 1 if time_left_hours > task_length_hours else 0


if __name__ == "__main__":
    # quickie
    example_deadline = "2026-08-15 10:30"
    example_length = 6 # hours

    result = is_time_left_greater(example_deadline, example_length)
    print(f"is_time_left_greater -> {result}")